#!/bin/zsh

setName=$1
#target=/afs/naf.desy.de/user/s/schettle/scratch/AnalysisTrees/whole2011_RA6
target=/scratch/hh/current/cms/user/schettle/AnalysisTrees/whole2011_RA6

if [ "$setName" = "" ]; then
	echo "please define setName or cancel [Ctrl c]."
	read setName
fi

go="n"

echo "merge DoubleMu set ${setName}? [y/n/all]"
read go

if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMu_May10_PRv4_05Aug_PRv6_RunB
    hadd -f ${target}/${setName}_DoubleMu_May10_PRv4_05Aug_PRv6_RunB/out.root \
	${target}/${setName}_DoubleMuMay10/out.root \
	${target}/${setName}_DoubleMuPRv4/out.root \
	${target}/${setName}_DoubleMu05Aug/out.root \
	${target}/${setName}_DoubleMuPRv6/out.root \
	${target}/${setName}_DoubleMuRunB/out.root
fi

if [ "$go" != "all" ]; then
    echo "merge DoubleElectron set ${setName}? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectron_May10_PRv4_05Aug_PRv6_RunB
    hadd -f ${target}/${setName}_DoubleElectron_May10_PRv4_05Aug_PRv6_RunB/out.root \
	${target}/${setName}_DoubleElectronMay10/out.root \
	${target}/${setName}_DoubleElectronPRv4/out.root \
	${target}/${setName}_DoubleElectron05Aug/out.root \
	${target}/${setName}_DoubleElectronPRv6/out.root \
	${target}/${setName}_DoubleElectronRunB/out.root
fi

if [ "$go" != "all" ]; then
    echo "merge MuEG set ${setName}? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_MuEG_May10_PRv4_05Aug_PRv6_RunB
    hadd -f ${target}/${setName}_MuEG_May10_PRv4_05Aug_PRv6_RunB/out.root \
        ${target}/${setName}_MuEGMay10/out.root \
        ${target}/${setName}_MuEGPRv4/out.root \
        ${target}/${setName}_MuEG05Aug/out.root \
        ${target}/${setName}_MuEGPRv6/out.root \
        ${target}/${setName}_MuEGRunB/out.root
fi

