#!/bin/zsh

setName=$1
#target=/afs/naf.desy.de/user/s/schettle/scratch/AnalysisTrees/whole2011_RA6
#target=/scratch/hh/current/cms/user/schettle/AnalysisTrees/whole2011_RA6
target=/scratch/hh/current/cms/user/schettle/AnalysisTrees/first2012_RA6

if [ "$setName" = "" ]; then
	echo "please define setName or cancel [Ctrl c]."
	read setName
fi

go="n"

echo "merge DoubleMu set ${setName}? [y/n/all]"
read go

if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMu_A_B_C
    hadd -f ${target}/${setName}_DoubleMu_A_B_C/out.root \
	${target}/${setName}_DoubleMuA/out.root \
	${target}/${setName}_DoubleMuB/out.root \
	${target}/${setName}_DoubleMuC/out.root
fi

if [ "$go" != "all" ]; then
    echo "merge DoubleElectron set ${setName}? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectron_A_B_C
    hadd -f ${target}/${setName}_DoubleElectron_A_B_C/out.root \
	${target}/${setName}_DoubleElectronA/out.root \
	${target}/${setName}_DoubleElectronB/out.root \
	${target}/${setName}_DoubleElectronC/out.root
fi

if [ "$go" != "all" ]; then
    echo "merge MuEG set ${setName}? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_MuEG_A_B_C
    hadd -f ${target}/${setName}_MuEG_A_B_C/out.root \
        ${target}/${setName}_MuEGA/out.root \
        ${target}/${setName}_MuEGB/out.root \
        ${target}/${setName}_MuEGC/out.root
fi

