#!/bin/bash

setName=$1
#target=/afs/naf.desy.de/user/s/schettle/scratch/AnalysisTrees/whole2011_RA6
target=/scratch/hh/current/cms/user/schettle/AnalysisTrees/whole2011_RA6
scriptLoc=/afs/naf.desy.de/user/s/schettle/macro/CMSSW_4_2_5/src/SUSYBSMAnalysis/DesySusy/examples/compiled/batch/
codeLoc=/afs/naf.desy.de/user/s/schettle/macro/CMSSW_4_2_5/src/SUSYBSMAnalysis/DesySusy/examples/compiled/whole2011_RA6

if [ "$setName" = "" ]; then
	echo "please define setName or cancel [Ctrl c]."
	read setName
fi

go="n"



if [ "$go" != "all" ]; then
    echo "run ${setName}_DoubleMuMay10? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMuMay10
    cd ${target}/${setName}_DoubleMuMay10
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleMu/Run2011A-May10ReReco-v1/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=6
fi


if [ "$go" != "all" ]; then
    echo "run ${setName}_DoubleMuPRv4? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMuPRv4
    cd ${target}/${setName}_DoubleMuPRv4
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleMu/Run2011A-PromptReco-v4/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=6
fi


if [ "$go" != "all" ]; then
    echo "run ${setName}_DoubleMu05Aug? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMu05Aug
    cd ${target}/${setName}_DoubleMu05Aug
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleMu/Run2011A-05Aug2011-v1 \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=4
fi


if [ "$go" != "all" ]; then
    echo run ${setName}_DoubleMuPRv6"? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMuPRv6
    cd ${target}/${setName}_DoubleMuPRv6
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleMu/Run2011A-PromptReco-v6/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=4
fi


if [ "$go" != "all" ]; then
    echo run ${setName}_DoubleMuRunB"? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleMuRunB
    cd ${target}/${setName}_DoubleMuRunB
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleMu/Run2011B-PromptReco-v1/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=8
fi


######################### E L E C T R O N S ############################


if [ "$go" != "all" ]; then
    echo "run ${setName}_DoubleElectronMay10? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectronMay10
    cd ${target}/${setName}_DoubleElectronMay10
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleElectron/Run2011A-May10ReReco-v1/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=6
fi


if [ "$go" != "all" ]; then
    echo "run ${setName}_DoubleElectronPRv4? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectronPRv4
    cd ${target}/${setName}_DoubleElectronPRv4
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleElectron/Run2011A-PromptReco-v4/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=6
fi


if [ "$go" != "all" ]; then
    echo "run ${setName}_DoubleElectron05Aug? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectron05Aug
    cd ${target}/${setName}_DoubleElectron05Aug
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleElectron/Run2011A-05Aug2011-v1 \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=4
fi


if [ "$go" != "all" ]; then
    echo run ${setName}_DoubleElectronPRv6"? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectronPRv6
    cd ${target}/${setName}_DoubleElectronPRv6
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleElectron/Run2011A-PromptReco-v6/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=4
fi


if [ "$go" != "all" ]; then
    echo run ${setName}_DoubleElectronRunB"? [y/n/all]"
    read go
fi
if [ "$go" = "y" -o "$go" = "all" ]; then
    mkdir ${target}/${setName}_DoubleElectronRunB
    cd ${target}/${setName}_DoubleElectronRunB
    ${scriptLoc}/./runOnAll \
	/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/data/DoubleElectron/Run2011B-PromptReco-v1/ \
	${codeLoc}/myAnalysis ${codeLoc}/data_config/config.txt cleanUp nFiles=8
fi