#!/bin/bash

setName=$1
#target=/afs/naf.desy.de/user/s/schettle/scratch/AnalysisTrees/whole2011_RA6
target=/scratch/hh/current/cms/user/schettle/AnalysisTrees/whole2011_RA6
scriptLoc=/afs/naf.desy.de/user/s/schettle/macro/CMSSW_4_2_5/src/SUSYBSMAnalysis/DesySusy/examples/compiled/batch
codeLoc=/afs/naf.desy.de/user/s/schettle/macro/CMSSW_4_2_5/src/SUSYBSMAnalysis/DesySusy/examples/compiled/whole2011_RA6

sampleCounter=1
sampleName[$sampleCounter]=TTJets
#sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/TTJets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v2/
sampleSource[$sampleCounter]=/scratch/hh/current/cms/user/schettle/nTuple11_v4/mc/TTJets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v2/
sampleConfig[$sampleCounter]=config_TTJets/config.txt
sampleNfiles[$sampleCounter]=7

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=TT_MCatNLO
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/TT_TuneZ2_7TeV-mcatnlo/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_TT_MCatNLO/config.txt
sampleNfiles[$sampleCounter]=5

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=DYJetsToLL_M-50
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_DYJetsToLL_M-50/config.txt
sampleNfiles[$sampleCounter]=6

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=DYJetsToLL_M-10To50
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/DYJetsToLL_M-10To50_TuneZ2_7TeV-madgraph/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_DYJetsToLL_M-10To50/config.txt
sampleNfiles[$sampleCounter]=7

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM1
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM1_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM1/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=WJetsToLNu
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_WJetsToLNu/config.txt
sampleNfiles[$sampleCounter]=17

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=ZZ
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/ZZ_TuneZ2_7TeV_pythia6_tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_ZZ/config.txt
sampleNfiles[$sampleCounter]=4

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=WW
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/WW_TuneZ2_7TeV_pythia6_tauola/Summer11-PU_S4_START42_V11-v1
sampleConfig[$sampleCounter]=config_WW/config.txt
sampleNfiles[$sampleCounter]=4

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=WZ
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/WZ_TuneZ2_7TeV_pythia6_tauola/Summer11-PU_S4_START42_V11-v1
sampleConfig[$sampleCounter]=config_WZ/config.txt
sampleNfiles[$sampleCounter]=4

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=ZZJetsTo4L
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/ZZJetsTo4L_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_ZZJetsTo4L/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=ZZJetsTo2L2Nu
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/ZZJetsTo2L2Nu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_ZZJetsTo2L2Nu/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=ZZJetsTo2L2Q
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/ZZJetsTo2L2Q_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_ZZJetsTo2L2Q/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=WZJetsTo3LNu
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/WZJetsTo3LNu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_WZJetsTo3LNu/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=WZJetsTo2L2Q
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/WZJetsTo2L2Q_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_WZJetsTo2L2Q/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=WWJetsTo2L2Nu
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/WWJetsTo2L2Nu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/
sampleConfig[$sampleCounter]=config_WWJetsTo2L2Nu/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=T_s
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/T_TuneZ2_s-channel_7TeV-powheg-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_T_s/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=T_t
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/T_TuneZ2_t-channel_7TeV-powheg-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_T_t/config.txt
sampleNfiles[$sampleCounter]=4

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=T_tW
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/T_TuneZ2_tW-channel-DS_7TeV-powheg-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_T_tW/config.txt
sampleNfiles[$sampleCounter]=2

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=Tbar_s
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/Tbar_TuneZ2_s-channel_7TeV-powheg-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_Tbar_s/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=Tbar_t
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/Tbar_TuneZ2_t-channel_7TeV-powheg-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_Tbar_t/config.txt
sampleNfiles[$sampleCounter]=2

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=Tbar_tW
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/Tbar_TuneZ2_tW-channel-DS_7TeV-powheg-tauola/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_Tbar_tW/config.txt
sampleNfiles[$sampleCounter]=2

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM2
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM2_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM2/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM3
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM3_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM3/config.txt
sampleNfiles[$sampleCounter]=10

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM4
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM4_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM4/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM5_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM5/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM6
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM6_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM6/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM7
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM7_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM7/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM8
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM8_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM8/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM9
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM9_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM9/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM11
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM11_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM11/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM12
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM12_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM12/config.txt
sampleNfiles[$sampleCounter]=1

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=LM13
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/schettle/nTuple11_v4/mc/LM13_SUSY_sftsht_7TeV-pythia6/Summer11-PU_S4_START42_V11-v2/
sampleConfig[$sampleCounter]=config_LM13/config.txt
sampleNfiles[$sampleCounter]=1

#####
#QCD#
#####

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-15to20_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-15to20_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v2
sampleConfig[$sampleCounter]=config_QCD_Pt-15to20_MuPt5/config.txt
sampleNfiles[$sampleCounter]=2

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-20to30_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-20to30_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v2
sampleConfig[$sampleCounter]=config_QCD_Pt-20to30_MuPt5/config.txt
sampleNfiles[$sampleCounter]=5

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-30to50_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-30to50_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v2
sampleConfig[$sampleCounter]=config_QCD_Pt-30to50_MuPt5/config.txt
sampleNfiles[$sampleCounter]=5

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-50to80_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-50to80_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1__2
sampleConfig[$sampleCounter]=config_QCD_Pt-50to80_MuPt5/config.txt
sampleNfiles[$sampleCounter]=5

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-80to120_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-80to120_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1
sampleConfig[$sampleCounter]=config_QCD_Pt-80to120_MuPt5/config.txt
sampleNfiles[$sampleCounter]=4

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-120to150_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-120to150_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1/
sampleConfig[$sampleCounter]=config_QCD_Pt-120to150_MuPt5/config.txt
sampleNfiles[$sampleCounter]=4

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-150_MuPt5
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-150_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1
sampleConfig[$sampleCounter]=config_QCD_Pt-150_MuPt5/config.txt
sampleNfiles[$sampleCounter]=3

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-20to30_EM
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-20to30_EMEnriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1__2
sampleConfig[$sampleCounter]=config_QCD_Pt-20to30_EM/config.txt
sampleNfiles[$sampleCounter]=8

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-30to80_EM
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-30to80_EMEnriched_TuneZ2_7TeV-pythia/Summer11-PU_S4_START42_V11-v1__2
sampleConfig[$sampleCounter]=config_QCD_Pt-30to80_EM/config.txt
sampleNfiles[$sampleCounter]=10

let sampleCounter=$sampleCounter+1
sampleName[$sampleCounter]=QCD_Pt-80to170_EM
sampleSource[$sampleCounter]=/pnfs/desy.de/cms/tier2/store/user/eron/nTuple11_v4/mc/QCD_Pt-80to170_EMEnriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1
sampleConfig[$sampleCounter]=config_QCD_Pt-80to170_EM/config.txt
sampleNfiles[$sampleCounter]=3

#let sampleCounter=$sampleCounter+1
#sampleName[$sampleCounter]=
#sampleSource[$sampleCounter]=
#sampleConfig[$sampleCounter]=config_
#sampleNfiles[$sampleCounter]=



if [ "$setName" = "" ]; then
	echo "please define setName or cancel [Ctrl c]."
	read setName
fi

goFor="n"

#echo "num samples ${sampleCounter}"

#for i in {1..$sampleCounter}; do
for (( i=1; i<=$sampleCounter; ++i )); do
#    echo $i
#    echo ${sampleName[$i]}
#    echo ${sampleSource[$i]}
#    echo ${sampleConfig[$i]}
#    echo ${sampleNfiles[$i]}


    if [ ! -n "${sampleName[$i]}" -o ! -n "${sampleSource[$i]}" -o ! -n "${sampleConfig[$i]}" -o ! -n "${sampleNfiles[$i]}" ]
    then
	echo CHECK YOUR SAMPLE SPECIFICATIONS! SOMTHING MISSING IN SAMPLE $i
	exit
    fi

    if [ "$goFor" != "all" ]; then
	goFor="n"
    fi

    if [ -d "${target}/${setName}_${sampleName[$i]}" ]; then
	echo dir ${target}/${setName}_${sampleName[$i]} already exists. Remove dir or choose another set name.
	goFor="exists"
    fi

    if [ "$goFor" != "all" -a "$goFor" != "exists" ]; then
	echo "run ${setName}_${sampleName[$i]}? [y/n/all]"
	read goFor
    fi  

    if [ "$goFor" = "y" -o "$goFor" = "all" ]; then
	mkdir ${target}/${setName}_${sampleName[$i]}
	cd ${target}/${setName}_${sampleName[$i]}
	${scriptLoc}/./runOnAll ${sampleSource[$i]} \
	    ${codeLoc}/myAnalysis ${codeLoc}/${sampleConfig[$i]} \
	    cleanUp nFiles=${sampleNfiles[$i]}
	echo
    fi
done




