#!/bin/bash
# to build up all sym links - links not to have the code at different places
function MakeLinks(){
        pushd  $1 > /dev/null
        ln -s ${here}/../NtupleTools2.h .
        ln -s ${here}/../NtupleTools2_h.h .
	ln -s ${here}/Linkdef.h .
        popd > /dev/null
}

here=$PWD

ln -s ../NtupleTools2.h .
ln -s ../NtupleTools2_h.h .

# list of subdirs <--------------------
list="simple multiple RA5 RA6 RA6b"

for i in $list; do
        MakeLinks $i
done


