#!/bin/bash 
#export SCRAM_ARCH=slc5_amd64_gcc462 
#CMSSW=CMSSW_5_3_3_patch2 
#cmsrel $CMSSW 
#cd $CMSSW/src 
#cmsenv 

# SusyPat
cvs co -r V00-03-16      CommonTools/ParticleFlow                         
cvs co -r V00-03-23      CommonTools/RecoAlgos                            
cvs co -r V00-00-13      CommonTools/RecoUtils
cvs co -r V15-03-02      DataFormats/ParticleFlowCandidate                
cvs co -r V06-05-06      DataFormats/PatCandidates                        
cvs co -r V00-02-14      DataFormats/StdDictionaries                      
cvs co -r V10-02-02      DataFormats/TrackReco                            
cvs co -r V02-00-04      DataFormats/VertexReco
cvs co -r V04-06-09      JetMETCorrections/Type1MET
cvs co -r V00-12-03      PhysicsTools/Configuration 
cvs co -r V08-09-23      PhysicsTools/PatAlgos
cvs co -r 1.6            PhysicsTools/PatAlgos/plugins/PATMHTProducer.h
cvs co -r V03-09-23      PhysicsTools/PatUtils
cvs co -r V15-01-11      RecoParticleFlow/PFProducer 

#MET filters (https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFilters) 
cvs co                   EventFilter/HcalRawToDigi/data/HCALLaser2012AllDatasets.txt.gz
cvs co -r V00-00-08      RecoMET/METAnalyzers                             
cvs co -r V00-00-13      RecoMET/METFilters

#Track POG Filters
cvs co -r V00-00-08      DataFormats/TrackerCommon
cvs co -r V00-11-17      DPGAnalysis/SiStripTools
cvs co -r V01-00-11-01   DPGAnalysis/Skims
cvs co -r V01-09-05      RecoLocalTracker/SubCollectionProducers

# functions to compute electron and photon IDs 
cvs co -r V00-00-31 -d EGamma/EGammaAnalysisTools UserCode/EGamma/EGammaAnalysisTools
cvs up -r 1.13 EGamma/EGammaAnalysisTools/interface/PFIsolationEstimator.h
cvs up -r 1.20 EGamma/EGammaAnalysisTools/src/PFIsolationEstimator.cc

#PileUp Jet ID
cvs co -r V00-03-01 -d CMGTools/External UserCode/CMG/CMGTools/External

#MET MVA and PileUp Jet ID
cvs co -r METPU_5_3_X_v8 JetMETCorrections/METPUSubtraction
cvs co -r HEAD -d pharrisTmp UserCode/pharris/MVAMet/data
cp  -d pharrisTmp/*Dec2012*.root           JetMETCorrections/METPUSubtraction/data/
rm -rf pharrisTmp

cvs co -r b5_3_X_cvMEtCorr_2013Feb22 DataFormats/METReco
cvs co -r V05-00-16      DataFormats/JetReco
cvs co -r V03-04-07      RecoMET/METAlgorithms
cvs co -r V03-03-12      RecoMET/METProducers
cvs co -r 1.6            PhysicsTools/PatAlgos/plugins/PATMHTProducer.h

#Tau Veto
cvs co -r V00-04-00      CondFormats/EgammaObjects
cvs co -r V01-04-10      RecoTauTag/Configuration                         
cvs co -r V01-04-23      RecoTauTag/RecoTau

cvs up -r 1.31.6.4 PhysicsTools/PatAlgos/python/producersLayer1/tauProducer_cfi.py
cvs up -r 1.52.10.4 PhysicsTools/PatAlgos/python/tools/tauTools.py

# pdf reweighting utilities ( needed for proper setup of lhapdffull https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEWKUtilities#Code_and_tags)
cvs co -r CMSSW_5_3_3_patch2 ElectroWeakAnalysis/Utilities

## TopAnalysis scripts (such as nafJobSplitter.pl)
cvs co -d TopAnalysis/TopUtils UserCode/Bromo/TopAnalysis/TopUtils

cvs co -dSUSYBSMAnalysis/SusyCAF -r V17-13 UserCode/SusyCAF
cvs co -dSUSYBSMAnalysis/DesySusy -r V00-18 UserCode/DesySusy

cp SUSYBSMAnalysis/DesySusy/nTuplePatch/susydesy_cfg.py SUSYBSMAnalysis/SusyCAF/test
cp SUSYBSMAnalysis/DesySusy/nTuplePatch/SusyDESY_nTuple_cfi.py SUSYBSMAnalysis/SusyCAF/python

# adding nominal pdf
unalias cp
cp -p SUSYBSMAnalysis/SusyCAF/plugins/mods/PdfWeightProducer.cc ElectroWeakAnalysis/Utilities/src/

scram setup lhapdffull
touch $CMSSW_BASE/src/ElectroWeakAnalysis/Utilities/BuildFile.xml #to ensure recompilation of the whole package

scram b -j16

