#!/bin/bash 
#export SCRAM_ARCH=slc5_amd64_gcc462 
#CMSSW=CMSSW_5_3_3_patch2 
#cmsrel $CMSSW 
#cd $CMSSW/src 
#cmsenv 

# SusyPat
addpkg CommonTools/ParticleFlow V00-03-16
addpkg CommonTools/RecoAlgos V00-03-23
addpkg CommonTools/RecoUtils V00-00-13
addpkg DataFormats/ParticleFlowCandidate V15-03-02
addpkg DataFormats/StdDictionaries V00-02-14
addpkg DataFormats/TrackReco V10-02-02
addpkg DataFormats/VertexReco V02-00-04
addpkg DataFormats/PatCandidates V06-05-06
addpkg PhysicsTools/PatAlgos V08-09-23
addpkg PhysicsTools/PatUtils V03-09-23
addpkg RecoParticleFlow/PFProducer V15-01-11                 
addpkg JetMETCorrections/Type1MET V04-06-09
addpkg PhysicsTools/Configuration V00-12-03

#MET filters (https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFilters) 
addpkg RecoMET/METAnalyzers V00-00-08 
addpkg RecoMET/METFilters V00-00-10

# functions to compute electron and photon IDs 
cvs co -r V00-00-31 -d EGamma/EGammaAnalysisTools UserCode/EGamma/EGammaAnalysisTools
cvs up -r 1.13 EGamma/EGammaAnalysisTools/interface/PFIsolationEstimator.h
cvs up -r 1.20 EGamma/EGammaAnalysisTools/src/PFIsolationEstimator.cc

#PileUp Jet ID
cvs co -r V00-03-01 -d CMGTools/External UserCode/CMG/CMGTools/External
#cvs co -r METPU_5_3_X_v4 RecoJets/JetProducers/data

#Tau Veto
addpkg CondFormats/EgammaObjects V00-04-00
addpkg RecoTauTag/RecoTau V01-04-23
addpkg RecoTauTag/Configuration V01-04-10

cvs up -r 1.31.6.4 PhysicsTools/PatAlgos/python/producersLayer1/tauProducer_cfi.py
cvs up -r 1.52.10.4 PhysicsTools/PatAlgos/python/tools/tauTools.py

# pdf reweighting utilities ( needed for proper setup of lhapdffull https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEWKUtilities#Code_and_tags)
cvs co -r CMSSW_5_3_3_patch2 ElectroWeakAnalysis/Utilities

## TopAnalysis scripts (such as nafJobSplitter.pl)
cvs co -d TopAnalysis/TopUtils UserCode/Bromo/TopAnalysis/TopUtils

cvs co -dSUSYBSMAnalysis/SusyCAF -r V17-13 UserCode/SusyCAF
cvs co -dSUSYBSMAnalysis/DesySusy -r V00-12 UserCode/DesySusy

cp SUSYBSMAnalysis/DesySusy/nTuplePatch/susydesy_cfg.py SUSYBSMAnalysis/SusyCAF/test
cp SUSYBSMAnalysis/DesySusy/nTuplePatch/SusyDESY_nTuple_cfi.py SUSYBSMAnalysis/SusyCAF/python

# adding nominal pdf
unalias cp
cp -p SUSYBSMAnalysis/SusyCAF/plugins/mods/PdfWeightProducer.cc ElectroWeakAnalysis/Utilities/src/

scram setup lhapdffull
touch $CMSSW_BASE/src/ElectroWeakAnalysis/Utilities/BuildFile.xml #to ensure recompilation of the whole package

scram b -j16

